import { readFileSync } from "node:fs";

/** Legacy URL redirects, generated from the catalog by scripts/build-redirects.ts. */
let legacyRedirects = [];
try {
  legacyRedirects = JSON.parse(
    readFileSync(new URL("./src/data/legacy-redirects.json", import.meta.url), "utf8"),
  );
} catch {
  // File is generated by the "prebuild" script; empty is a safe fallback.
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  // Pin the tracing root to THIS project (a stray package-lock.json exists in the
  // home directory, which would otherwise be inferred as the workspace root).
  outputFileTracingRoot: import.meta.dirname,
  images: {
    // All content imagery is local and rights-cleared or an explicit fallback.
    // Remote image sources are intentionally disallowed (no remotePatterns).
    formats: ["image/webp"],
  },
  async redirects() {
    // Legacy TanStack/Lovable routes -> canonical routes (real 308s).
    return legacyRedirects;
  },
};

export default nextConfig;
