import { readFileSync } from "node:fs";

/** Approved image host: the project's Supabase Storage (future admin uploads only). */
const supabaseHost = (() => {
  try {
    return process.env.NEXT_PUBLIC_SUPABASE_URL
      ? new URL(process.env.NEXT_PUBLIC_SUPABASE_URL).host
      : null;
  } catch {
    return null;
  }
})();

/** Legacy URL redirects, generated from the catalog by scripts/build-redirects.ts. */
let legacyRedirects = [];
try {
  legacyRedirects = JSON.parse(
    readFileSync(new URL("./src/data/legacy-redirects.json", import.meta.url), "utf8"),
  );
} catch {
  // File is generated by the "prebuild" script; empty is a safe fallback.
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  // Pin the tracing root to THIS project (a stray package-lock.json exists in the
  // home directory, which would otherwise be inferred as the workspace root).
  outputFileTracingRoot: import.meta.dirname,
  images: {
    // Launch imagery is local & rights-cleared. The ONLY permitted remote host is
    // this project's Supabase Storage bucket (future admin uploads) — nothing else.
    formats: ["image/webp"],
    remotePatterns: supabaseHost
      ? [{ protocol: "https", hostname: supabaseHost, pathname: "/storage/v1/object/public/**" }]
      : [],
  },
  async redirects() {
    // Legacy TanStack/Lovable routes -> canonical routes (real 308s).
    return legacyRedirects;
  },
  async headers() {
    // Keep the hidden admin area out of indexes and caches.
    return [
      {
        source: "/internal/:path*",
        headers: [
          { key: "X-Robots-Tag", value: "noindex, nofollow, noarchive" },
          { key: "Cache-Control", value: "no-store, max-age=0, must-revalidate" },
          { key: "Referrer-Policy", value: "no-referrer" },
        ],
      },
    ];
  },
};

export default nextConfig;
