/**
 * Generates src/data/hotel-image-map.ts from .image-work/fetch-results.json.
 * Verified hotel images are promoted to status "verified_local" so lib/images.ts
 * resolves them on the public pages (replacing the destination fallback).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Fetched = {
  slug: string;
  status: string;
  source_url?: string;
  original_url?: string;
  caption?: string;
  image?: string;
  thumbnail?: string;
};

const ROOT = process.cwd();
const results: Fetched[] = JSON.parse(
  readFileSync(join(ROOT, ".image-work", "fetch-results.json"), "utf8"),
);

const verified = results.filter((r) => r.status === "verified_local" && r.image);
// de-dupe by slug (last write wins)
const bySlug = new Map<string, Fetched>();
for (const r of verified) bySlug.set(r.slug, r);

const entries = [...bySlug.values()]
  .sort((a, b) => a.slug.localeCompare(b.slug))
  .map(
    (r) =>
      `  ${JSON.stringify(r.slug)}: {\n` +
      `    image: ${JSON.stringify(r.image)},\n` +
      `    thumbnail: ${JSON.stringify(r.thumbnail)},\n` +
      `    status: "verified_local",\n` +
      `    sourceUrl: ${JSON.stringify(r.source_url ?? "")},\n` +
      `  },`,
  )
  .join("\n");

const out = `/**
 * hotel slug -> resolved image override. GENERATED by scripts/apply-fetched-images.ts.
 *
 * The ONLY place that promotes a hotel from a destination fallback to a real
 * image. Entries below are identity-verified hero photos downloaded from the
 * hotels' official pages (ELBAKRI OVERSEAS is authorized to use them) and
 * optimized locally. Re-run \`tsx scripts/apply-fetched-images.ts\` to refresh.
 */

export type HotelImageStatus =
  | "admin_uploaded"
  | "verified_local"
  | "destination_fallback"
  | "placeholder";

export type HotelImageMapEntry = {
  image: string;
  thumbnail?: string;
  status: HotelImageStatus;
  sourceUrl?: string;
};

const hotelImageMap: Record<string, HotelImageMapEntry> = {
${entries}
};

export default hotelImageMap;
`;

writeFileSync(join(ROOT, "src", "data", "hotel-image-map.ts"), out);
console.log(`✓ hotel-image-map.ts written with ${bySlug.size} verified hotel images`);
