/**
 * Generates src/data/hotel-image-map.ts and src/data/honeymoon-image-map.ts
 * from the fetch-results in .image-work. Only images that actually exist on
 * disk are promoted (drops any bad/removed download). Re-run after fetching.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Fetched = {
  slug: string;
  status: string;
  kind?: string;
  source_url?: string;
  image?: string;
  thumbnail?: string;
  kb_main?: number;
};

const ROOT = process.cwd();
const PUBLIC = join(ROOT, "public");

function load(file: string): Fetched[] {
  const p = join(ROOT, ".image-work", file);
  return existsSync(p) ? JSON.parse(readFileSync(p, "utf8")) : [];
}

const combined = [
  ...load("fetch-results.json").map((r) => ({ ...r, kind: r.kind ?? "hotel" })),
  ...load("fetch-results2.json"),
];

const verified = combined.filter(
  (r) => r.status === "verified_local" && r.image && existsSync(join(PUBLIC, r.image)),
);

function mapEntry(slug: string, image: string, thumb: string | undefined, source: string) {
  return (
    `  ${JSON.stringify(slug)}: {\n` +
    `    image: ${JSON.stringify(image)},\n` +
    `    thumbnail: ${JSON.stringify(thumb ?? image.replace(/hotels\/[^/]+/, "thumbnails").replace(/.*\//, "/images/thumbnails/"))},\n` +
    `    status: "verified_local",\n` +
    `    sourceUrl: ${JSON.stringify(source)},\n` +
    `  },`
  );
}

/* ---------- hotels ---------- */
const hotels = new Map<string, Fetched>();
for (const r of verified.filter((r) => r.kind === "hotel")) hotels.set(r.slug, r);

const hotelEntries = [...hotels.values()]
  .sort((a, b) => a.slug.localeCompare(b.slug))
  .map((r) => mapEntry(r.slug, r.image!, r.thumbnail, r.source_url ?? ""))
  .join("\n");

writeFileSync(
  join(ROOT, "src", "data", "hotel-image-map.ts"),
  `/**
 * hotel slug -> real image. GENERATED by scripts/apply-fetched-images.ts.
 * Identity-verified hero photos from each hotel's official page (ELBAKRI
 * OVERSEAS holds full usage rights). Optimized locally.
 */

export type HotelImageStatus =
  | "admin_uploaded"
  | "verified_local"
  | "destination_fallback"
  | "placeholder";

export type HotelImageMapEntry = {
  image: string;
  thumbnail?: string;
  status: HotelImageStatus;
  sourceUrl?: string;
};

const hotelImageMap: Record<string, HotelImageMapEntry> = {
${hotelEntries}
};

export default hotelImageMap;
`,
);

/* ---------- honeymoon ---------- */
// Honeymoon deals that ARE a destination hotel already imaged -> reuse that file.
const REUSE: Record<string, { image: string; thumb: string; src: string }> = {
  "pickalbatros-royal-moderna": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-royal-moderna.webp",
    thumb: "/images/thumbnails/pickalbatros-royal-moderna.webp",
    src: "https://www.pickalbatros.com/royal-moderna-resort-sharm-el-sheikh",
  },
  "pickalbatros-royal-grand": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-royal-grand.webp",
    thumb: "/images/thumbnails/pickalbatros-royal-grand.webp",
    src: "https://www.pickalbatros.com/royal-grand-resort-sharm-el-sheikh",
  },
  "pickalbatros-sea-world": {
    image: "/images/hotels/marsa-alam/pickalbatros-sea-world.webp",
    thumb: "/images/thumbnails/pickalbatros-sea-world.webp",
    src: "https://www.pickalbatros.com/sea-world-resort-marsa-alam",
  },
};

const honeymoon = new Map<string, { image: string; thumb: string; src: string }>();
for (const [slug, v] of Object.entries(REUSE)) {
  if (existsSync(join(PUBLIC, v.image))) honeymoon.set(slug, v);
}
for (const r of verified.filter((r) => r.kind === "honeymoon")) {
  honeymoon.set(r.slug, {
    image: r.image!,
    thumb: r.thumbnail ?? `/images/thumbnails/${r.slug}.webp`,
    src: r.source_url ?? "",
  });
}

const hmEntries = [...honeymoon.entries()]
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([slug, v]) => mapEntry(slug, v.image, v.thumb, v.src))
  .join("\n");

writeFileSync(
  join(ROOT, "src", "data", "honeymoon-image-map.ts"),
  `/**
 * honeymoon deal slug -> real image. GENERATED by scripts/apply-fetched-images.ts.
 * Deals that are the same physical property as a destination hotel reuse that
 * hotel's verified file (no duplicate download).
 */
import type { HotelImageMapEntry } from "./hotel-image-map";

const honeymoonImageMap: Record<string, HotelImageMapEntry> = {
${hmEntries}
};

export default honeymoonImageMap;
`,
);

console.log(
  `✓ hotel-image-map: ${hotels.size} hotels · honeymoon-image-map: ${honeymoon.size} deals`,
);
