/**
 * honeymoon deal slug -> real image. GENERATED by scripts/apply-fetched-images.ts.
 * Deals that are the same physical property as a destination hotel reuse that
 * hotel's verified file (no duplicate download).
 */
import type { HotelImageMapEntry } from "./hotel-image-map";

const honeymoonImageMap: Record<string, HotelImageMapEntry> = {
  "pickalbatros-citadel": {
    image: "/images/hotels/honeymoon/pickalbatros-citadel.webp",
    thumbnail: "/images/thumbnails/pickalbatros-citadel.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/citadel-resort-sahl-hasheesh",
  },
  "pickalbatros-royal-grand": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-royal-grand.webp",
    thumbnail: "/images/thumbnails/pickalbatros-royal-grand.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/royal-grand-resort-sharm-el-sheikh",
  },
  "pickalbatros-royal-moderna": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-royal-moderna.webp",
    thumbnail: "/images/thumbnails/pickalbatros-royal-moderna.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/royal-moderna-resort-sharm-el-sheikh",
  },
  "pickalbatros-sea-world": {
    image: "/images/hotels/marsa-alam/pickalbatros-sea-world.webp",
    thumbnail: "/images/thumbnails/pickalbatros-sea-world.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/sea-world-resort-marsa-alam",
  },
};

export default honeymoonImageMap;
