/**
 * hotel slug -> resolved image override. GENERATED by scripts/apply-fetched-images.ts.
 *
 * The ONLY place that promotes a hotel from a destination fallback to a real
 * image. Entries below are identity-verified hero photos downloaded from the
 * hotels' official pages (ELBAKRI OVERSEAS is authorized to use them) and
 * optimized locally. Re-run `tsx scripts/apply-fetched-images.ts` to refresh.
 */

export type HotelImageStatus =
  | "admin_uploaded"
  | "verified_local"
  | "destination_fallback"
  | "placeholder";

export type HotelImageMapEntry = {
  image: string;
  thumbnail?: string;
  status: HotelImageStatus;
  sourceUrl?: string;
};

const hotelImageMap: Record<string, HotelImageMapEntry> = {
  "beach-albatros": {
    image: "/images/hotels/hurghada/beach-albatros.webp",
    thumbnail: "/images/thumbnails/beach-albatros.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/beach-albatros-resort-hurghada",
  },
  "pickalbatros-alf-leila-wa-leila": {
    image: "/images/hotels/hurghada/pickalbatros-alf-leila-wa-leila.webp",
    thumbnail: "/images/thumbnails/pickalbatros-alf-leila-wa-leila.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/alf-leila-wa-leila-resort-neverland-hurghada",
  },
  "pickalbatros-aqua-blu-hurghada": {
    image: "/images/hotels/hurghada/pickalbatros-aqua-blu-hurghada.webp",
    thumbnail: "/images/thumbnails/pickalbatros-aqua-blu-hurghada.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/aqua-blu-resort-hurghada",
  },
  "pickalbatros-aqua-blu-sharm-el-sheikh": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-aqua-blu-sharm-el-sheikh.webp",
    thumbnail: "/images/thumbnails/pickalbatros-aqua-blu-sharm-el-sheikh.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/aqua-blu-resort-sharm-el-sheikh",
  },
  "pickalbatros-aqua-park-hurghada": {
    image: "/images/hotels/hurghada/pickalbatros-aqua-park-hurghada.webp",
    thumbnail: "/images/thumbnails/pickalbatros-aqua-park-hurghada.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/aqua-park-resort-hurghada",
  },
  "pickalbatros-aqua-park-sharm-el-sheikh": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-aqua-park-sharm-el-sheikh.webp",
    thumbnail: "/images/thumbnails/pickalbatros-aqua-park-sharm-el-sheikh.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/aqua-park-resort-sharm-el-sheikh",
  },
  "pickalbatros-aqua-vista": {
    image: "/images/hotels/hurghada/pickalbatros-aqua-vista.webp",
    thumbnail: "/images/thumbnails/pickalbatros-aqua-vista.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/aqua-vista-resort-hurghada",
  },
  "pickalbatros-dana-beach": {
    image: "/images/hotels/hurghada/pickalbatros-dana-beach.webp",
    thumbnail: "/images/thumbnails/pickalbatros-dana-beach.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/dana-beach-resort-hurghada",
  },
  "pickalbatros-jungle-aqua-park": {
    image: "/images/hotels/hurghada/pickalbatros-jungle-aqua-park.webp",
    thumbnail: "/images/thumbnails/pickalbatros-jungle-aqua-park.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/jungle-aqua-park-resort-neverland-hurghada",
  },
  "pickalbatros-laguna-club": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-laguna-club.webp",
    thumbnail: "/images/thumbnails/pickalbatros-laguna-club.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/laguna-club-resort-sharm-el-sheikh",
  },
  "pickalbatros-laguna-vista": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-laguna-vista.webp",
    thumbnail: "/images/thumbnails/pickalbatros-laguna-vista.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/laguna-vista-hotel-sharm-el-sheikh",
  },
  "pickalbatros-oasis": {
    image: "/images/hotels/marsa-alam/pickalbatros-oasis.webp",
    thumbnail: "/images/thumbnails/pickalbatros-oasis.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/oasis-hotel-port-ghalib",
  },
  "pickalbatros-palace": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-palace.webp",
    thumbnail: "/images/thumbnails/pickalbatros-palace.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/palace-resort-sharm-el-sheikh",
  },
  "pickalbatros-porto-fino": {
    image: "/images/hotels/marsa-alam/pickalbatros-porto-fino.webp",
    thumbnail: "/images/thumbnails/pickalbatros-porto-fino.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/villaggio-resort-portofino-marsa-alam",
  },
  "pickalbatros-royal-grand": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-royal-grand.webp",
    thumbnail: "/images/thumbnails/pickalbatros-royal-grand.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/royal-grand-resort-sharm-el-sheikh",
  },
  "pickalbatros-royal-moderna": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-royal-moderna.webp",
    thumbnail: "/images/thumbnails/pickalbatros-royal-moderna.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/royal-moderna-resort-sharm-el-sheikh",
  },
  "pickalbatros-sands": {
    image: "/images/hotels/marsa-alam/pickalbatros-sands.webp",
    thumbnail: "/images/thumbnails/pickalbatros-sands.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/sands-hotel-port-ghalib",
  },
  "pickalbatros-sea-world": {
    image: "/images/hotels/marsa-alam/pickalbatros-sea-world.webp",
    thumbnail: "/images/thumbnails/pickalbatros-sea-world.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/sea-world-resort-marsa-alam",
  },
  "pickalbatros-sharm": {
    image: "/images/hotels/sharm-el-sheikh/pickalbatros-sharm.webp",
    thumbnail: "/images/thumbnails/pickalbatros-sharm.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/albatros-sharm-resort-sharm-el-sheikh",
  },
  "pickalbatros-vita": {
    image: "/images/hotels/marsa-alam/pickalbatros-vita.webp",
    thumbnail: "/images/thumbnails/pickalbatros-vita.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/vita-resort-portofino-marsa-alam",
  },
  "pickalbatros-water-valley": {
    image: "/images/hotels/hurghada/pickalbatros-water-valley.webp",
    thumbnail: "/images/thumbnails/pickalbatros-water-valley.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/water-valley-resort-neverland-hurghada",
  },
  "pickalbatros-white-beach": {
    image: "/images/hotels/hurghada/pickalbatros-white-beach.webp",
    thumbnail: "/images/thumbnails/pickalbatros-white-beach.webp",
    status: "verified_local",
    sourceUrl: "https://www.pickalbatros.com/white-beach-resort-hurghada",
  },
};

export default hotelImageMap;
